from django.urls import path
from . import views
from .views import (PostList,
                    news_list,
                    PostCreate,
                    article_list,
                    PostUpdate,
                    PostDelete,
                    CategoryList,
                    ProfileList,
                    subscriptions,
                    post_detail,
                    CategoryDetail,
                    view_list_posts_in_category)
from django.conf import settings
from django.conf.urls.static import static
# from django.views.decorators.cache import cache_page


urlpatterns = [
     path('',
          PostList.as_view(),
          name='HomePage'),
     path('posts/list/detail/<int:pk>/<slug:slug>',
          views.post_detail,
          name='PostDetail'),
     path('news/list/',
          views.news_list,
          name='NewsList'),
     path('news/list/detail/<int:pk>/<slug:slug>',
          views.post_detail,
          name='NewsDetail'),
     path('articles/list/',
          views.article_list,
          name='ArticlesList'),
     path('articles/list/detail/<int:pk>/<slug:slug>',
          views.post_detail,
          name='ArticlesDetail'),
     path('create/',
          PostCreate.as_view(),
          name='PostCreate'),
     path('posts/list/detail/<int:pk>/<slug:slug>/update',
          PostUpdate.as_view(),
          name='PostUpdate'),
     path('news/list/detail/<int:pk>/<slug:slug>/update',
          PostUpdate.as_view(),
          name='PostUpdate'),
     path('articles/list/detail/<int:pk>/<slug:slug>/update',
          PostUpdate.as_view(),
          name='PostUpdate'),
     path('posts/list/detail/<int:pk>/<slug:slug>/delete',
          PostDelete.as_view(),
          name='PostDelete'),
     path('news/list/detail/<int:pk>/<slug:slug>/delete',
          PostDelete.as_view(),
          name='PostDelete'),
     path('articles/list/detail/<int:pk>/<slug:slug>/delete',
          PostDelete.as_view(),
          name='PostDelete'),
     path('categories/list/',
          CategoryList.as_view(),
          name='CategoryList'),
     path('accounts/login/profile',
          ProfileList.as_view(),
          name='profile'),
     path('subscriptions/',
          views.subscriptions,
          name='subscriptions'),
     path('categories/list/<int:pk>/<slug:slug>',
          views.view_list_posts_in_category,
          name='ListPostsInCategory'),
     path('categories/detail/<int:pk>/<slug:slug>',
          CategoryDetail.as_view(),
          name='CategoryDetail')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
