# Generated by Django 5.1 on 2024-08-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post_id',
            new_name='post',
        ),
    ]
