# Generated by Django 5.1 on 2024-08-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0003_alter_comment_user_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Пост/Категория', 'verbose_name_plural': 'Посты/Категории'},
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='newsportal.PostCategory', to='newsportal.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('NS', 'Новость'), ('AT', 'Статья')], default='NS', max_length=2),
        ),
    ]
