# Generated by Django 5.1 on 2024-11-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0005_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/'),
        ),
    ]
